### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by wassimz** [rtrompier/jhipster-ng2admin#1]
Hi,
I have tried to run the project but I got exception when running __yarn start__
Any hint ??

**Comment by rtrompier** [comment]
Hi wassimz,

It's an old project.
Jhipster team have updated the Angular 2 project.

You should start from this latest version ;)

Otherwise, can you send me the error. I can try to check ;)

++


--

*Rémy TROMPIER*
 6 Chemin de Valavran, 01210 Ferney-Voltaire, France
 remy-trompier.fr <http://www.remy-trompier.fr/>   +33(0) 678 491 740
<http://0033678491740/>+41(0) 79 558 62 76 <callto:0041795586276>

This email may contain confidential and / or privileged informations.
If you are not the intended recipient (or have received this email in
error) please notify the sender immediately and destroy this email.
Unauthorized reproduction, disclosure or distribution of elements contained
in this email is strictly prohibited.

2017-04-29 22:22 GMT+02:00 wassimz <notifications@github.com>:

**Comment by wassimz** [comment]
I was thought this project is using already Angular2. Anyway as I am new to Angular I wa thinking to integrate ng2admin with Jhipster.

When I run the command `yarn install` and `yarn start` I got this error:

> C:\Users\Desktop\jhipster-ng2admin-master\node_modules\webpack-dev-server\lib\Server.js:25
        const validationErrors = webpack.validateSchema(optionsSchema, options);
                                  ^
TypeError: webpack.validateSchema is not a function
    at new Server (C:\Users\wassimz\Desktop\jhipster-ng2admin-master\node_modules\webpack-dev-server\lib\Server.js:25:35)
    at startDevServer (C:\Users\wassimz\Desktop\jhipster-ng2admin-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js:358:12)
    at processOptions (C:\Users\wassimz\Desktop\jhipster-ng2admin-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js:322:3)
    at Object.<anonymous> (C:\Users\wassimz\Desktop\jhipster-ng2admin-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js:430:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

and when I run `mvn -Pprod clean package` I got
> INFO] Child extract-text-webpack-plugin:
[INFO]                                     Asset     Size  Chunks             Chunk Names
[INFO]      19e65b89cee273a249fba4c09b951b74.eot   121 kB          [emitted]
[INFO]      28df6ee7b407fd8a14b40bc01f4fd3ae.svg   334 kB          [emitted]
[INFO]      dd4781d1acc57ba4c4808d1b44301201.ttf   189 kB          [emitted]
[INFO]     2c159d0d05473040b53ec79df8797d32.woff  67.9 kB          [emitted]
[INFO]         + 6 hidden modules
[ERROR]
[ERROR] npm ERR! Windows_NT 6.1.7601
[ERROR] npm ERR! argv "C:\\Users\\Desktop\\jhipster-ng2admin-master\\node\\node.exe" "C:\\Users\\wassimz\\Desktop\\jhipster-ng2admin-master\\node\\node_modules\\npm\\bin\\np
m-cli.js" "run" "webpack" "--" "--config" "config/webpack.prod.js"
[ERROR] npm ERR! node v4.6.0
